apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: intel-qat-plugin
spec:
  template:
    spec:
      initContainers:
      - name: sriov-numvfs
        image: intel/intel-qat-initcontainer:0.24.0
        securityContext:
          readOnlyRootFilesystem: true
          privileged: true
        volumeMounts:
        - name: sysfs
          mountPath: /sys
      volumes:
      - name: sysfs
        hostPath:
          path: /sys
